# Generated by Django 5.1.6 on 2025-03-05 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=10)),
                ('country', models.CharField(choices=[('Tunisie', 'Tunisie'), ('France', 'France'), ('Allemagne', 'Allemagne'), ('Italie', 'Italie'), ('Espagne', 'Espagne'), ('États-Unis', 'États-Unis'), ('Canada', 'Canada'), ('Royaume-Uni', 'Royaume-Uni')], default='Tunisie', max_length=100)),
            ],
        ),
    ]
