# Generated by Django 5.1.6 on 2025-03-07 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_user_reset_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='reset_token',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
